- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 Instance
      ec2_instance:
        instance_type: t3.medium
        image_id: ami-04e5276ebb8451442
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-0b96ad66b9afaed82
        tags:
          Name: Eshop
        count: 1
        network:
          assign_public_ip: yes
        wait: yes
        security_group: eshop
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        security_token: '{{ session_token }}'
      register: ec2_instance_result

    - name: Add instance host to group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      loop: "{{ ec2_instance_result.instances }}"

    - name: Wait for SSH connection
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2_instance_result.instances }}"

- name: Configure EC2 Instances
  hosts: launched
  connection: ssh
  become: yes
  

  tasks:
    - name: Install Git and Docker
      yum:
        name:
          - git
          - docker
        state: latest
        update_cache: yes
    - service:
        name: docker
        state: started
        enabled: yes

    - name: Set proper rights to Docker service
      shell: usermod -a -G docker ec2-user

    - name: Fetch eshop from Git
      git:
        repo: 'https://github.com/TPackT/vse_devops_final.git'
        dest: ./app

    - name: Build Eshop Docker image
      docker_image:
        build:
          path: ./app
        name: eshop
        tag: latest
        source: build
    - name: Run Eshop Docker
      docker_container:
        name: eshop
        image: eshop
        state: started
        ports:
          - "80:3000"

    - name: Wait for eshop to run
      wait_for:
        port:
          80

##----------------------------------- terminate previous instances

- name: Terminate previous EC2 instances
  hosts: localhost
  connection: local

  tasks:
    - name: Find all running instances via tag
      ec2_instance_info:
        filters:
          'tag:Name': 'Eshop'
          'instance-state-name': 'running'
        region: us-east-1
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        security_token: '{{ session_token }}'
      register: all_instances

    - name: Sort instances by launch time
      set_fact:
        instances_list: "{{ all_instances.instances | sort(attribute='launch_time', reverse=true) | map(attribute='instance_id') }}"
      when: all_instances.instances | length > 0

    - name: Exclude last created instance
      set_fact:
        instances_to_terminate: '{{ instances_to_terminate + [item] }}'
      loop: '{{ instances_list[1:] }}'
      vars:
        instances_to_terminate: []
      when: instances_list | length > 0

    - name: Terminate instances
      ec2_instance:
        state: 'absent'
        instance_ids: '{{ instances_to_terminate }}'
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        security_token: '{{ session_token }}'
        region: us-east-1
      when: instances_to_terminate and instances_to_terminate | length > 0

